name: 2. PR feature to develop

on:
  workflow_run:
    workflows: [ '1. Build & Test' ]
    types: [ completed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  call-pr-to-develop:
    name: Criando PR de feature para develop
    uses: barbarastefany/reusable-workflows/.github/workflows/2-pr-to-develop.yml@main
    with:
        base-branch: ${{ github.event.workflow_run.head_branch }}
        target-branch: 'develop'
    secrets: inherit