name: Call 3. Manual Merge PR to Develop
on:
  workflow_run:
    workflows:
      - 'Call 2. Create PR to Develop'
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-pr-to-develop:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: barbarastefany/reusable-workflows/.github/workflows/3-merge-to-develop.yml@main
    with:
      pr-number: ${{ github.event.workflow_run.pull_requests[0].number }}
    secrets: inherit