name: Call 3. Merge PR to Develop and 4. Create PR to Main

on:
  workflow_run:
    workflows:
      - 'Call 2. Create PR to Develop'
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-pr-to-develop:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Merge PR to Develop
    uses: barbarastefany/reusable-workflows/.github/workflows/3-merge-to-develop.yml@main
    with:
      pr-number: ${{ github.event.workflow_run.head_branch }}
    secrets: inherit

  pr-develop-to-main:
    needs: merge-pr-to-develop
    name: Create PR from Develop to Main
    uses: barbarastefany/reusable-workflows/.github/workflows/4-pr-to-main.yml@main
    with:
      merged-pr-number: ${{ needs.merge-pr-to-develop.outputs.merged-pr-number }}
    secrets: inherit