name: 3. Merge PR to Develop and Call 4

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  call-4-pr-to-main:
    if: contains(github.event.head_commit.message, 'Merge pull request')
    uses: barbarastefany/reusable-workflows/.github/workflows/4-pr-to-main.yml@main
    with:
      merged-pr-number: ''
    secrets: inherit
