name: 3. PR develop to main

on:
  workflow_run:
    workflows: [ '2. PR feature to develop' ]
    types: [ completed ]
    branches: [ 'develop' ]

permissions:
  contents: write
  pull-requests: write

jobs:
  call-pr-to-main:
    name: Criando PR de develop para main
    uses: barbarastefany/reusable-workflows/.github/workflows/3-pr-to-main.yml@main
    secrets: inherit
